### ISSUE TITLE
Feature | Create a new docker image for Leverage CLI

### ISSUE THREAD

**Issue by angelofenoglio** [binbashar/le-docker-images#85]
## Rationale

Currently the tool uses `terraform-awscli-slim` to execute the different commands. The image not only contains terraform and awscli as implied in the name, but also, scripts to handle aws credentials and other useful tooling.

The versioning for this image, and as a consequence, the tagging strategy, is tied to the version of terraform for which the image was built. In case a developer needs to implement changes in the previously mentioned scripts, or in any other of the tools in the image, it is forced into two scenarios.
1. Waiting for a new terraform release to push these changes
2. Replace the image in the registry with the current tag with a new, updated image, effectively voiding the previous version of the image.

This last point also creates an additional issue regarding the updating of the already pulled images. It becomes difficult for leverage-cli to determine whether the image currently in the system is the last version or not. Manually deleting the local image to force leverage to pull it again is the current way of fixing this issue. This in turn, makes it impossible to truly pin a version making repeatability quite challenging.

## Proposal

A docker image called `leverage-cli`. Dockerfile and all auxiliary resources stored in a directory with the same name as is the convention in this repository.
The image should contain the same tooling and scripts the current one holds, the difference should be made in the tagging strategy.
Tagging following semantic versioning to correctly identify small fixes/improvements, new features and breaking changes could be a good practice.
This also solves the issues stated previously regarding ease of upgrading and version pinning.

This approach, in turn obfuscates a little more the contents of the image. Maintaining a changelog in the image's directory in this repository can be a solution. Also, to ease access to this changelog by users of the docker hub, a permanent link to the file can be added to the main README.

## Additional Context
https://faun.dev/c/stories/bellam/why-should-we-care-about-semantic-versioning/

**Comment by angelofenoglio** [comment]
@diego-ojeda-binbash @exequielrafaela Any additional input is greatly appreciated!

**Comment by exequielrafaela** [comment]
@angelofenoglio thanks for creating this topic with such a clear level of detail. As agreed and reflected at the [`leverage cli` roadmap](https://binbash.atlassian.net/wiki/spaces/BDPS/pages/2196799489/Product+Roadmap+2022) let's plan and prioritize when possible to create and move this very important docker image with the new semver proposed in a dedicated repo. 

CC: @diego-ojeda-binbash

**Comment by exequielrafaela** [comment]
@angelofenoglio @juanmatias  Based on our discussion we'll move forward with a concatenated `terraform_ver-sem-ver` format eg: `1.1.9-0.0.1` for the new release management strategy in the stand-alone leverage cli docker image.

```
# Project settings
PROJECT=bb

# General
MFA_ENABLED=false

# Terraform
LEVERAGE_IMAGE_TAG=1.1.9-0.0.1
```

CC: @diego-ojeda-binbash

**Comment by juanmatias** [comment]
@angelofenoglio , sharing thoughts on this topic....


# Table of Contents

1.  [Facts](#org0b93ada)
2.  [What to ensure](#org3acad21)
3.  [About the container images](#orgbb6c947)
4.  [Proposal](#org419bd4f)
    1.  [1 - Terraform and CLI Compatibility versions in the container version space](#org29f2cd2)
    2.  [2 - Terraform version in the name](#orgeae583f)
    3.  [3 - Terraform and CLI Compatibility versions in name](#org4e65734)
    4.  [4 - Terraform agnostic image](#org033eeb7)

Thoughts on how to tag Leverage container images.


<a id="org0b93ada"></a>

# Facts

A given Leverage CLI is tied to a minimum Terraform version and to a set of scripts.


<a id="org3acad21"></a>

# What to ensure

-   The client should be able to chose Terraform version (from the available ones)
-   The used image should grant a script-set minimum version (related to the CLI version, this will be called CLI Compatibility version)


<a id="orgbb6c947"></a>

# About the container images

The way to name a container image (or a tag to one) is:

    $USERNAME/$IMAGENAME:$VERSION

It is possible to get a specific container image (the first part splitting by the colon) using the \`latest\` version.

Sometimes it is not recommended to use \`latest\`, but sometimes it ensures the image contains the last security patches.


<a id="org419bd4f"></a>

# Proposal

All the following keeping in mind that the Terraform version selection and CLI compatibility is the main goal to reach. (e.g. for CLI \`v1.7.2\` uses Terraform \`>= 1.1.9\` and other scripts)


<a id="org29f2cd2"></a>

## 1 - Terraform and CLI Compatibility versions in the container version space

In this case this can be used:

    $USERNAME/$IMAGENAME:${TERRAFORM_VERSION}-${IMAGE_VERSION}

Here, the IMAGE<sub>VERSION</sub> should grant the &ldquo;other scripts&rdquo; minimum versions.

In this case the \`latest\` tag can not be used due to the chance of it having a different Terraform version that the one the client has selected.


<a id="orgeae583f"></a>

## 2 - Terraform version in the name

In this case this can be used:

    $USERNAME/$IMAGENAME/${TERRAFORM_VERSION}:${IMAGE_VERSION}

In this case, for a given Terraform version there are a number of versions, the \`latest\` can be used maintaining the Terraform version but (since Docker and similar engines do not support wildcards in the version), the version matching a CLI can not be asured. (e.g. using CLI \`v1.7.2\` should match, let&rsquo;s say, the image version \`1.7.\*\`, if \`latest\` jumps to \`1.8.0\` the version matching is lost)


<a id="org4e65734"></a>

## 3 - Terraform and CLI Compatibility versions in name

In this case this can be used:

    $USERNAME/$IMAGENAME/${TERRAFORM_VERSION}-${CLI_COMPATIBILITY_VERSION}:${IMAGE_VERSION}

This way a CLI Compatibility brand should be set.

E.g., the CLI \`v1.7.2\` is compatible with the image series named as &ldquo;1.7&rdquo;, containing in the name also the Terraform version:

    binbashar/leverage/terra1.4-le1.7:${IMAGE_VERSION}

This way, for a given Terraform Version and a CLI Compatibility series, the tag \`latest\` can be used to fetch the latest image (i.e. the one including the last security patches and fixes), for the installed CLI version keeping the selected Terraform version.


<a id="org033eeb7"></a>

## 4 - Terraform agnostic image

In this case this can be used:

    $USERNAME/$IMAGENAME/${CLI_COMPATIBILITY_VERSION}:${IMAGE_VERSION}

In this case a tool such as \`tfenv\` can be used internally to switch terraform versions on-the-fly using just one image. The image still requires the CLI Compatibility version set in the name for keeping CLI-image compatibility while allowing fetching \`latest\`.

For a given \`CLI<sub>COMPATIBILITY</sub><sub>VERSION</sub>\` a set of Terraform version are offered.

Finally, setting an envvar such as \`TF<sub>VERSION</sub>\` the Terraform version can be set internally once the image is running.

A final notes in this item 4 are:

-   This same approach can be used for other tools.
-   To avoid problems using different Terraform versions with already existing tfstates, the Terraform version can be fixed in the Terraform files and then checked while running (e.g. having a flag \`&#x2013;force-new-terraform-version\` or something like this to upgrade versions)

**Comment by exequielrafaela** [comment]
@juanmatias regarding the before presented naming and tagging strategies as we've discussed probably as a 1st iteration going for the `binbashar/leverage:tf_version-cli_version` could be the simplest and most efficient 1st iteration:

Eg:

- `binbashar/leverage:1.1.9-0.0.1`
- `binbashar/leverage:1.2.1-0.0.1` (latest)

We release a patch
- `binbashar/leverage:1.1.9-0.0.2`
- `binbashar/leverage:1.2.1-0.0.2` (latest)

One more important thing to review and define will be to permanently move, track and version the associated [**bash aws credentials management scripts**](https://github.com/binbashar/le-docker-images/blob/fe7f0a9c19eeb526603e9c51e4f4ff8b90f6e49a/terraform-awscli-slim/Dockerfile#L48) to this new leverage docker image repository

CC: @angelofenoglio @diego-ojeda-binbash @binbashar/leverage-ref-architecture-aws-admin @binbashar/leverage-ref-architecture-aws-dev

**Comment by exequielrafaela** [comment]
@juanmatias dedicated repo https://github.com/binbashar/le-docker-leverage has been created.
